development: &default
  adapter: postgresql
  database: stackoverflow_clone_development
  username: rails
  password: rails
  encoding: utf8
  host: localhost
  pool: 5
  timeout: 5000

test:
  <<: *default
  database: stackoverflow_clone_test

production:
  url: <%= ENV['DATABASE_URL'] %>
  pool: <%= ENV['DB_POOL'] || ENV['MAX_THREADS'] || 5 %>
